apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec: 
  addresses:
  - 192.168.50.20-192.168.50.28
  autoAssign: true
  avoidBuggyIPs: true
